name: extify
description: "Lightweight Dart extension utilities for String, Number, DateTime, List, and more â€” with Korean language support"
version: 1.0.2
homepage: https://github.com/seungjoonH/extify
repository: https://github.com/seungjoonH/extify

environment:
  sdk: ^3.5.4

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
